import os
import shutil

# Input dataset
input_dataset = '/home/Student/s4582342/ConGD/data'

# Define the splits (train, val, test)
splits = ['train', 'val', 'test']

# Combine videos in each split to generate format similar to AUTSL dataset
# Generated by OpenAI's ChatGPT
for split in splits:
    split_dir = os.path.join(input_dataset, split)

    # Iterate through subdirectories within the split directory
    for root, _, files in os.walk(split_dir):
        for file in files:
            # Get the full path of the file
            file_path = os.path.join(root, file)

            # Define the new destination path within the split directory
            dest_path = os.path.join(split_dir, file)

            # Move the file to the new destination path
            shutil.move(file_path, dest_path)

    # Remove empty subdirectories within the split directory
    for root, dirs, _ in os.walk(split_dir, topdown=False):
        for dir_name in dirs:
            dir_path = os.path.join(root, dir_name)
            os.rmdir(dir_path)
