import csv
import os

# Input and output files
input_file = '/home/Student/s4582342/ConGD/data/test.txt'
output_file = '/home/Student/s4582342/ConGD/data/test_labels.csv'

# Generate format similar to AUTSL labels. That is, filenames in first column and corresponding labels in second column
# Generated by OpenAI's ChatGPT
with open(input_file, 'r') as txt_file:
    # Read the lines from the .txt file
    lines = txt_file.readlines()

    # Create a list to store the rows for the .csv file
    csv_rows = []

    # Process each line
    for line in lines:
        # Split the line based on whitespace to extract video_name and [start,end:label]
        parts = line.strip().split()

        if len(parts) >= 2:
            video_name = parts[0].split('/')[-1]  # Extract the part after the '/'
            labels = ' '.join(parts[1:])

            # Modify the video_name to match the desired format
            video_name = f"{video_name}.M.mp4"

            # Append the video_name and labels to the list as a tuple
            csv_rows.append((video_name, labels))

# Write the data to the output .csv file without headers
with open(output_file, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerows(csv_rows)

