import cv2
import os

# Function to count the number of frames in a video file
# Generated by OpenAI's ChatGPT
def count_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return frame_count

# Remove .mp4 files with frame number > 150
# Generated by OpenAI's ChatGPT
def remove_videos(directory_path):
    for root, dirs, files in os.walk(directory_path):
        for file in files:
            if file.endswith(".mp4"):
                video_path = os.path.join(root, file)
                frame_count = count_frames(video_path)
                if frame_count > 150:
                    print(f"Removing video '{file}' from '{directory_path}' with {frame_count} frames.")
                    os.remove(video_path)

# Input dataset
root_directory = '/home/Student/s4582342/ConGD/data_old'

# Call functions for each of the splits
splits = ["train", "val", "test"]
for split in splits:
    split_directory = os.path.join(root_directory, split)
    remove_videos(split_directory)
