import os

# Define input dataset and new dataset path
# Update according to analysed dataset
input_dataset = '/home/Student/s4582342/ConGD'
output_dataset = '/home/Student/s4582342/ConGD/data'

# Define splits
splits = ['train', 'val', 'test']

# Convert a video file from .avi to .mp4
# Generated by OpenAI's ChatGPT
def convert_video(input_path, output_path):
    os.system(f'ffmpeg -i {input_path} -c:v libx264 -crf 23 -c:a aac -strict experimental -b:a 192k {output_path}')

# Iterate through each split and process the videos
for split in splits:
    input_split_dir = os.path.join(input_dataset, split)
    output_split_dir = os.path.join(output_dataset, split)

    # Check if the output split directory already exists, and if so, skip this split
    if os.path.exists(output_split_dir):
        print(f'Split {split} already exists, skipping...')
        continue

    # Create the output split directory
    os.makedirs(output_split_dir, exist_ok=True)

    # Iterate through subdirectories (e.g., '001')
    for subdir in os.listdir(input_split_dir):
        subdir_path = os.path.join(input_split_dir, subdir)

        # List all .avi files in the subdirectory
        avi_files = [f for f in os.listdir(subdir_path) if f.endswith('.avi')]

        # Iterate through .avi files and convert them to .mp4 format
        for avi_file in avi_files:
            input_video_path = os.path.join(subdir_path, avi_file)
            output_video_name = os.path.splitext(avi_file)[0] + '.mp4'
            output_video_path = os.path.join(output_split_dir, subdir, output_video_name)

            # Create the output subdirectory if it doesn't exist
            os.makedirs(os.path.dirname(output_video_path), exist_ok=True)

            # Convert .avi to .mp4
            convert_video(input_video_path, output_video_path)
