import csv
import os

# Define input .txt file and location to write output .csv file
input_file = '/home/Student/s4582342/data/test.txt'
output_file = '/home/Student/s4582342/data/test_labels.csv'

# Convert .txt file to .csv file with format filenames in first column and corresponding labels in second column
# Generated by OpenAI's ChatGPT
with open(input_file, 'r') as txt_file, open(output_file, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file, delimiter=',')

    # Iterate through each line in the .txt file
    for line in txt_file:
        # Split the line into RGB_video_name, depth_video_name, and GestureLabel
        rgb_video_name, depth_video_name, gesture_label = line.strip().split()

        # Extract the desired information (M_00001.avi and GestureLabel)
        rgb_video_name = os.path.splitext(rgb_video_name.split('/')[-1])[0] + '.mp4'

        # Write the extracted information to the .csv file
        csv_writer.writerow([rgb_video_name, gesture_label])
