import os

# Define input dataset
# Change according to analysed dataset
input_dataset = '/home/Student/s4582342/data_avi'


# Delete .avi files starting with 'K'
# Generated by OpenAI's ChatGPT
def delete_files_with_prefix(directory):
    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)
        if filename.lower().endswith('.avi') and filename.startswith('K'):
            os.remove(file_path)
            print(f"Deleted file: {file_path}")


# Iterate through the training, validation, and test splits
splits = ['train', 'val', 'test']
for split in splits:
    split_dir = os.path.join(input_dataset, split)

    # Check if the split directory exists
    if not os.path.exists(split_dir):
        continue

    # Iterate through gesture class directories within the split
    for gesture_class in os.listdir(split_dir):
        gesture_class_dir = os.path.join(split_dir, gesture_class)

        # Check if the gesture class directory exists
        if not os.path.isdir(gesture_class_dir):
            continue

        # Delete .avi files with filenames starting with 'K' in the gesture class directory
        delete_files_with_prefix(gesture_class_dir)
