import os
import csv
import pickle

# Input csv and output csv, as well as input pkl
input_csv = '/home/Student/s4582342/LSE/data/test_labels.csv'
output_csv = '/home/Student/s4582342/LSE/data/test_labels_final.csv'
input_pkl = '/home/Student/s4582342/LSE/MSSL_TEST_SET_GT.pkl'

# Create a dictionary to store label data
label_data = {}

# Read label data from the single .pkl file and store it in the dictionary
with open(input_pkl, 'rb') as label_file:
    label_data = pickle.load(label_file)

# Read the original CSV file and create the updated CSV data
# Generated by OpenAI's ChatGPT
updated_csv_data = []
with open(input_csv, 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        filename = row[0][:8]  # Extract the first 8 characters of the filename
        if filename in label_data and label_data[filename]:
            # Update the second column with label data
            label_info = label_data[filename]
            label_entry = label_info.pop(0)
            label_string = str(label_entry)  # Convert the list to a string
            row[1] = label_string
        else:
            # If no label data is available or the label list is empty, leave the second column empty
            row[1] = ''
        updated_csv_data.append(row)

# Write the updated CSV data to the new CSV file
with open(output_csv, 'w', newline='') as new_csv_file:
    csv_writer = csv.writer(new_csv_file)
    csv_writer.writerows(updated_csv_data)
